services:
  db:
    container_name: pg_container_boilerplate
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
    ports:
      - '5922:5432'

  db-test:
    container_name: pg_container_boilerplate_test
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - '5933:5432'

  adminer:
    container_name: adminer_container_boilerplate
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - '5903:8080'
